---
title: "TimeSeriesOnlyPCV10"
output: pdf_document
date: "2025-07-14"
---

```{r}
library(ggtext)
```


```{r}
nepalGps = read.csv("nepal_gps.csv")
nepalNonGps = read.csv("nepal.csv")
```


Filtering the time series analysis for only PCV-10 serotypes

```{r}
pcv10Serotypes1 <- c('1', '4', '5', '6B', '7F', '9V', '14', '18C', '19F', '23F')
GpsShortened <- nepalGps[, c("Year", "Clinical_manifestation", "In_silico_serotype")]

pcv10Serotypes2 <- c('PCV10serotypes')
nonGpsShortened <- nepalNonGps[nepalNonGps$Serotype %in% pcv10Serotypes2, ]

NONpcv10Serotypes <- c('3', '6A', '19A', '22F', '33F', '8', '10A', '11A', '12F', '15B', 'Other')

NONPCVforGPS <- nepalNonGps[nepalNonGps$Serotype %in% NONpcv10Serotypes, ]
```



```{r}
# Pivoting the non gps dataset
pcv10NonGpsCarriage <- nonGpsShortened %>%
  # Selecting year columns
  dplyr::select(X2014n, X2015n, X2017n, X2018n, X2019n, X2021n) %>%
  # Formating data frame
  pivot_longer(cols = everything(),
               names_to = "Year",
               values_to = "Count") %>%
  # Removing X and n from the year counts
  mutate(Year = gsub("X|n", "", Year)) %>%
  group_by(Year) %>%
  slice_tail()

# Pivoting the non gps dataset
NonPCVForOffset <- NONPCVforGPS %>%
  # Selecting year columns
  dplyr::select(X2014n, X2015n, X2017n, X2018n, X2019n, X2021n) %>%
  # Formating data frame
  pivot_longer(cols = everything(),
               names_to = "Year",
               values_to = "Count") %>%
  # Removing X and n from the year counts
  mutate(Year = gsub("X|n", "", Year)) %>%
  group_by(Year) %>%
  slice_tail()
```


```{r}
# Adding a new column that will be whether or not the serotype was in pcv10 or not
GpsShortened$PCV10_group <- ifelse(GpsShortened$In_silico_serotype %in% pcv10Serotypes1,"PCV10", "Non-PCV10")

# Selecting only pcv10
pcv10GpsCarriage <- GpsShortened[GpsShortened$PCV10_group == "PCV10", ]

NONpcv10GpsCarriage <- GpsShortened[GpsShortened$PCV10_group == "Non-PCV10", ]

```

```{r}
pcv10GpsCarriage2 <- pcv10GpsCarriage %>%
  filter(Clinical_manifestation == "CARRIAGE") %>%
  group_by(Year) %>%
  dplyr::summarize(IPDCount = n())

NONpcv10GpsCarriage2 <- NONpcv10GpsCarriage %>%
  filter(Clinical_manifestation == "CARRIAGE") %>%
  group_by(Year) %>%
  dplyr::summarize(IPDCountNONPCV10 = n())
```

```{r}
mergedPcv10CarriageDf <- merge(pcv10NonGpsCarriage, pcv10GpsCarriage2, by = "Year", all = TRUE)
mergedPcv10CarriageDf

mergedNONpcv10CarriageDf <- merge(NonPCVForOffset, NONpcv10GpsCarriage2, by = "Year", all = TRUE)
mergedNONpcv10CarriageDf
```

```{r}
# Adding the total counts for carriage
mergedPcv10CarriageDf$CCount <- rowSums(mergedPcv10CarriageDf[, c("Count", "IPDCount")], na.rm = TRUE)
mergedPcv10CarriageDf

mergedNONpcv10CarriageDf$CCountNONPCV10 <- rowSums(mergedNONpcv10CarriageDf[, c("Count", "IPDCountNONPCV10")], na.rm = TRUE)
mergedNONpcv10CarriageDf
```

```{r}
# Loading in the typhoid data set used for offset
typhoidDf = read.csv("typhoidMetadata.csv")
typhoidDf
```


```{r}
# Renaming the year column for easy merging
names(typhoidDf)[names(typhoidDf) == "year"] <- "Year"
```

```{r}
t2 <- typhoidDf %>%
  # Filtering out the years we don't want
  filter(Year > 2008 & Year < 2019) %>%
  group_by(Year) %>%
  dplyr::summarize(typhoidCount = n())
```

```{r}
# Adding the typhoid counts to the nepal IPD dataset
mergedDF <- merge(mergedPcv10CarriageDf, t2, by = "Year")
mergedDF

mergedDfNONPCV10 <- merge(mergedPcv10CarriageDf, mergedNONpcv10CarriageDf, by = "Year")
mergedDfNONPCV10
```

```{r}
# Selecting the only columns we need
analysisDf <- mergedDF %>%
  dplyr::select(Year, CCount, typhoidCount) %>%
  filter(Year != 2014)

analysisDf

analysis2Df <- mergedDfNONPCV10 %>%
  dplyr::select(Year, CCount, CCountNONPCV10) %>%
  filter(Year != 2014)
analysis2Df
```

METHOD TWO

```{r}
method2 <- tibble::rownames_to_column(analysisDf, var = "index") %>%
 mutate(index = as.numeric(index))
```


```{r}
# Changing the eval date because there is no 2016
vax.intro.date <- as.Date('2015-01-01')
vax.intro.year <- format(vax.intro.date, "%Y")

vax.eval.date <- as.Date('2017-01-01')
vax.eval.year <- format(vax.eval.date, "%Y")

intro.index <- which(method2$Year == year(vax.intro.date))
eval.index <- which(method2$Year == year(vax.eval.date))

intro.index <- as.numeric(intro.index)
eval.index <- as.numeric(eval.index)

method2 <- method2 %>%
  mutate(
    spl1 = ifelse(index - intro.index + 1 < 0, 0, index - intro.index + 1),
    spl2 = ifelse(index - eval.index + 1 < 0, 0, index  - eval.index + 1)
  )

# Inspect the changes.
method2[c("Year", "index", "spl1", "spl2")]
```

```{r}
# Creating the offsets by selecting all tyhpoid cases
method2$log.offset <- log(method2$typhoidCount)
```


```{r}
#method2 <- method2 %>%
#  filter(Year != 2014)
mod2 <- glm.nb(CCount ~ index  + offset(log.offset) +
                 # Post-vaccine changes.
                 spl1 + spl2, data = method2)

summary(mod2)
```

```{r}
## Generate the factual model

# Make predictions with confidence intervals.
method2.pred.spl <- method2 %>%
  mutate(pred.spl = predict(mod2, type = "response"))


## --------------------
## Generate the counterfactual model

# Initialize the vacccine effect variables by setting them to 0.
method2.counterfactual.spl <- method2
method2.counterfactual.spl$spl1 <- 0
method2.counterfactual.spl$spl2 <- 0

# Generate the fitted values.
method2.pred.spl$pred.spl.cf <- predict(mod2, type = "response", 
                                   newdata = method2.counterfactual.spl)


## --------------------
## Rate ratio to evaluate performance

# Generate the rate ratio between the fitted and counterfactual values.
method2.pred.spl$rr.spline <- method2.pred.spl$pred.spl/method2.pred.spl$pred.spl.cf
```

```{r}
## --------------------
## Prepare a plot to visualize the factual model predictions

# Make predictions with confidence intervals.
pred2 <- predict(mod2, type = "response", se.fit = TRUE)

# Add the model predictions and 95% COI to the dataframe.
method2.pred.spl <- method2.pred.spl %>%
  mutate(se.fit = pred2$se.fit, pred = pred2$fit) %>%
  mutate(
    conf.low = pred - 1.96 * se.fit,
    conf.high = pred + 1.96 * se.fit
  )


p_m2 <- 
  ggplot(method2.pred.spl, aes(x = Year, y = CCount)) +
      geom_point() +
      # Add the fitted line.
      geom_line(data = method2.pred.spl, aes(x = Year, y = pred.spl, group = 1),
                color = "#377eb8") +
      # Add the confidence interval.
      geom_ribbon(data = method2.pred.spl, aes(ymin = conf.low, ymax = conf.high),
                  alpha = 0.2, fill = "blue", group = 1) +
      # Add the counterfactual line.
      geom_line(data = method2.pred.spl, aes(x = Year, y = pred.spl.cf),
                color = "#e41a1c", lty = 2, group = 1)  +
  labs(title = "Pneumoccocal Carriage Infections in Nepal",
      subtitle = "Negative Binomial Fit,\nInterrupted Time Series with Spline Smoothing",
         x = "Year", y = "Counts") +
      theme_linedraw()

p_m2
```

```{r}
# Inspect methods sensitivity to vaccine impact.

p_ratio <- ggplot() +
     geom_line(data = method2.pred.spl, aes(x = Year, y = rr.spline), group = 1,
               color = "#4daf4a") +
      # Update the title.
      labs(title = "Rate Ratio with the Spline Model")

p_ratio
```

METHOD TWO but with nonpcv 10

```{r}
method22 <- tibble::rownames_to_column(analysis2Df, var = "index") %>%
 mutate(index = as.numeric(index))
```

```{r}
# Changing the eval date because there is no 2016
vax.intro.date <- as.Date('2015-01-01')
vax.intro.year <- format(vax.intro.date, "%Y")

vax.eval.date <- as.Date('2017-01-01')
vax.eval.year <- format(vax.eval.date, "%Y")

intro.index <- which(method22$Year == year(vax.intro.date))
eval.index <- which(method22$Year == year(vax.eval.date))

intro.index <- as.numeric(intro.index)
eval.index <- as.numeric(eval.index)

method22 <- method22 %>%
  mutate(
    spl1 = ifelse(index - intro.index + 1 < 0, 0, index - intro.index + 1),
    spl2 = ifelse(index - eval.index + 1 < 0, 0, index  - eval.index + 1)
  )

# Inspect the changes.
method22[c("Year", "index", "spl1", "spl2")]
```

```{r}
# Creating the offsets by selecting all nonpcv10 cases
method22$log.offset <- log(method22$CCountNONPCV10)
```

```{r}
mod2 <- glm.nb(CCount ~ index  + offset(log.offset) +
                 # Post-vaccine changes.
                 spl1 + spl2, data = method22)

summary(mod2)

# Count of carriage cases = index + log offset + index starting at vaccine introduction year + index starting at vaccine evaluation year

#index - intro.index + 1

# carriage cases ~ year index + log(offset) + vaccine intro spline + vaccine evaluation spline
```

```{r}
## Generate the factual model

# Make predictions with confidence intervals.
method22.pred.spl <- method22 %>%
  mutate(pred.spl = predict(mod2, type = "response"))


## --------------------
## Generate the counterfactual model

# Initialize the vacccine effect variables by setting them to 0.
method22.counterfactual.spl <- method22
method22.counterfactual.spl$spl1 <- 0
method22.counterfactual.spl$spl2 <- 0

# Generate the fitted values.
method22.pred.spl$pred.spl.cf <- predict(mod2, type = "response", 
                                   newdata = method22.counterfactual.spl)


## --------------------
## Rate ratio to evaluate performance

# Generate the rate ratio between the fitted and counterfactual values.
method22.pred.spl$rr.spline <- method22.pred.spl$pred.spl/method22.pred.spl$pred.spl.cf
```

```{r}
# Make predictions with confidence intervals.
pred2 <- predict(mod2, type = "response", se.fit = TRUE)

# Add the model predictions and 95% COI to the dataframe.
method22.pred.spl <- method22.pred.spl %>%
  mutate(se.fit = pred2$se.fit, pred = pred2$fit) %>%
  mutate(
    conf.low = pred - 1.96 * se.fit,
    conf.high = pred + 1.96 * se.fit
  )

method22.pred.spl$Year <- as.numeric(method22.pred.spl$Year)

p_m2 <- 
  ggplot(method22.pred.spl, aes(x = Year, y = CCount)) +
      geom_point(aes(color = "Observed Cases")) +
      # Add the fitted line.
      geom_line(data = method22.pred.spl, aes(x = Year, y = pred.spl, group = 1, color = "Fitted Line"), size = .7) +
      # Add the confidence interval.
      geom_ribbon(data = method22.pred.spl, aes(ymin = conf.low, ymax = conf.high, fill = "95% CI"),
                  alpha = 0.2, group = 1) +
      # Add the counterfactual line.
      geom_line(data = method22.pred.spl, aes(x = Year, y = pred.spl.cf, color = "Counterfactual"),
                lty = 2, group = 1, size = .8)  +
  labs(title = "Time Series Analysis - Pneumococcal Carriage Infections",
      subtitle = paste0(
    "<span style='font-size:12pt'>Negative Binomial Fit, Interrupted Time Series with Spline Smoothing</span><br>",
    "<span style='font-size:1pt; color:white'>&nbsp;</span><br>",
    "<span style='font-size:12pt; color:#6A0DAD'>Carriage Cases ~ Year Index + log(Offset) + Vaccine Intro Spline + Vaccine Eval Spline</span>"
  ), x = "Year", y = "Cases"
  ) +
      theme_linedraw() +
  geom_vline(xintercept = 2015, color = "red", linetype = "dashed", size = .8) +

    scale_color_manual(name='Legend',
                     breaks=c('Fitted Line', 'Counterfactual', "Observed Cases"),
                     values=c("Fitted Line" = "#00356B","Counterfactual" = "#E69F00", "Observed Cases" = "black")) +
  scale_fill_manual(name='Legend',
                     breaks=c('95% CI'),
                     values=c("95% CI" = "#008080")) + 
      # Specify aspects of the theme plot formatting settings.
      theme(panel.spacing = unit(2, 'lines'), 
            axis.text.x = element_text(angle = 0, size = 12, vjust = 3, margin = margin(t = 10)),
            axis.text.y = element_text(size = 12, vjust = 3),
            axis.title = element_text(size = 12),
            axis.title.x = element_text(size = 14),
            axis.title.y =element_text(size = 14),
            plot.title = element_text(size = 15, face = "bold"),
            legend.position = "bottom",
            plot.subtitle = element_markdown(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 12)) +
    scale_x_continuous(
    breaks = seq(
      floor(min(method22.pred.spl$Year, na.rm = TRUE)),
      ceiling(max(method22.pred.spl$Year, na.rm = TRUE)),
      by = 1
    )) +             
  annotate("text", x = 2015.15, y = 00.1, label = "Vaccine Introduced", color = "red", hjust = 0)

p_m2
ggsave(filename="time_series.jpeg", plot=p_m2, width=8, height=5)
```


keeping offset as data with the same limitations, tracking the pneumoccocal population overtime
```{r}
# Inspect methods sensitivity to vaccine impact.

p_ratio <- ggplot() +
     geom_line(data = method22.pred.spl, aes(x = Year, y = rr.spline), group = 1,
               color = "#4daf4a") +
      # Update the title.
      labs(title = "Rate Ratio with the Spline Model")

p_ratio
```

